name: Build SesameAG APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Find all apk files
        run: find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SesameAG-APK
          path: ./**/*.apk

